<?php

namespace AppBundle\Repository;

/**
 * ContactAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
