<?php

namespace AppBundle\Repository;

/**
 * ContactMessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactMessagesRepository extends \Doctrine\ORM\EntityRepository
{
}
