<?php

namespace AppBundle\Repository;

/**
 * WorldCityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorldCityRepository extends \Doctrine\ORM\EntityRepository
{
}
