app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /

root:
    path: /
    defaults:
        _controller: FrameBundle:Redirect:urlRedirect
        path: /
        permanent: true